apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: desirable-pinniped-go 
  janus-idp.io/tekton: desirable-pinniped-go
  backstage.io/kubernetes-id: desirable-pinniped-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: desirable-pinniped-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  